version: '3.7'

services:
    iris:
      build:
        context: ./iris
        dockerfile: Dockerfile
      restart: always
      hostname: iris
      command: --password-file password.txt --check-caps false
      ports:
        - 51773:51773
        - 52773:52773
        - 53773:53773
      expose:
        - "51773"

    app:
      build: ./app
      restart: always
      volumes:
        - ./app:/app
      depends_on:
        - iris
      links:
        - iris
      ports:
        - 8011:8011

    client:
      build: ./client
      restart: always
      volumes:
        - ./client:/client
        - /client/node_modules
      depends_on:
        - app
      links:
        - app
      ports:
        - 8080:8080
